# Generated by Django 4.2.2 on 2023-12-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mar_returned', 'Set Book as returned'),)},
        ),
    ]
